.TH JOTAFETCH 1 "April 2026" "jotafetch 1.0.0" "jotafetch manual"
.SH NAME
jotafetch \- A neofetch-like utility made by Jotalea
.SH SYNOPSIS
.B jotafetch
.SH DESCRIPTION
.B jotafetch
is a simple system information tool written in bash. It displays basic information about your operating system, kernel, shell, and hardware.
.SH OPTIONS
This utility does not have any command-line options.
.SH SEE ALSO
.BR neofetch (1)
.SH AUTHORS
Jotalea
.SH BUGS
Report bugs to the project repository.
.SH LICENSE
MIT License
